jobs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.list, name="job_list"),
    url(r'submit/$', views.create, name="job_create"),
    url(r'thanks/$', views.thanks, name="job_thanks"),
    url(r'(?P<slug>[\w-]+)/$', views.detail, name="job_detail"),
]

pybay/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from django.contrib import admin

import symposion.views
from symposion.teams import urls as teams_urls
from symposion.proposals import urls as proposals_urls
from symposion.sponsorship import urls as sponsor_urls
from symposion.speakers import urls as speaker_urls

from pybay import views
from pybay.proposals import views as preview_views


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"


faq_view = views.FaqTemplateView.as_view


urlpatterns = [
    url(r"^$", views.FrontpageView.as_view(faq_filter="show_on_home"), name="home"),
    # url(r"^cfp$", views.pybay_cfp_create, name="pybay_cfp"),
    # url(r'^call-for-proposals/$', RedirectView.as_view(pattern_name='pybay_cfp', permanent=False)),
    url(r"^sponsors-prospectus/$", faq_view(template_name="frontend/sponsors_prospectus.html", faq_filter="show_on_sponsors"), name="pybay_sponsors"),
    url(r'^sponsors/$', RedirectView.as_view(pattern_name='pybay_sponsors', permanent=False)),
    url(r"^code-of-conduct$", TemplateView.as_view(template_name="frontend/code_of_conduct.html"), name="pybay_coc"),
    url(r"^coc-reporting$", TemplateView.as_view(template_name="frontend/coc_reporting.html"), name="pybay_coc_reporting"),
    url(r"^registration$", RedirectView.as_view(url='https://ti.to/sf-python/pybay2019')),
    url(r"^faq$", views.pybay_faq_index, name="pybay_faq"),

    url(r"^admin/", include(admin.site.urls)),
    url(r"^admin/blockstuff/docs", TemplateView.as_view(template_name="blockstuff/docs.html")),
    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),

    url(r"^account/", include("account.urls")),
    #url(r"^speaker/", include(speaker_urls)),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    url(r"^proposals/", include(proposals_urls)),
    url(r"^talks/", preview_views.index, name="pybay_preview"),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^boxes/", include("pinax.boxes.urls")),

    url(r"^schedule/", views.pybay_schedule, name='pybay_schedule'),
    url(r"^schedule-sym/", include("symposion.schedule.urls")),
    # url(r"^account/signup/$", SignupView.as_view(), name="account_signup"),
    # url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
    # url(r"^teams/", include(teams_urls)),
    # url(r"^teams/", include("symposion.teams.urls")),
    # url(r"^markitup/", include("markitup.urls")),
    url(r"^our-sponsors/$", views.pybay_sponsors_list, name="pybay_sponsors_list"),
    url(r"^our-speakers/$", views.pybay_speakers_list, name="pybay_speakers_list"),
    url(r"^speaker/(?P<speaker_slug>[-\w]+)/$", views.pybay_speakers_detail, name="pybay_speakers_detail"),
    url(r"^api/undecided_proposals$", views.undecided_proposals, name="pybay_undecided_proposals"),
    url(r"^api/proposals/(?P<proposal_id>\d+)/$", views.proposal_detail, name="pybay_detail_proposal"),
    url(r"^404$", TemplateView.as_view(template_name="404.html")),  # Adding explicitly for template dev purposes
    url(r"^jobs/", include("jobs.urls")),
    url(r"^registration$", RedirectView.as_view(url='https://ti.to/sf-python/pybay2019'), name='pybay_tickets'),
    # url(r"^", include("symposion.cms.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

jobs/models.py
from django.db import models

from ordered_model.models import OrderedModel

ORDERING_CHOICES = [(3500, 'Platinum'), (2000, 'Diamond'), (1500, 'Gold'), (1000, 'Silver'), (500, 'Bronze'), (0, 'None')]

class VisibleJobManager(models.Manager):
    def get_queryset(self):
        return super(VisibleJobManager, self).get_queryset().filter(display=True)
    def all(self):
      return super(VisibleJobManager, self).all().order_by('-level', 'order')

class Job(OrderedModel):
    class Meta:
        verbose_name = 'Job Details'
        verbose_name_plural = 'Job Postings'

    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255, default="", help_text="Employer name.")
    contact_email = models.EmailField(max_length=255,
                                      help_text="Not shared publicly. Be sure to use the email"
                                                " associated with your Paypal account.",
                                      default="")
    contact_phone = models.CharField(max_length=20, help_text="Not shared publicly.", default="")
    display = models.BooleanField(help_text="Show this job posting on the site.", default=False)
    logo = models.ImageField(upload_to="logos", blank=True)
    url = models.SlugField(help_text="Give the posting a short slug to be used in the url")
    details = models.TextField("Summary", help_text="Short and punchy text")
    lengthy_details = models.TextField("Details", blank=True, help_text="The rest of the details. Use markdown for bulleted lists, *italics*, etc.")
    link = models.CharField(max_length=255, default="", help_text="Add a link to apply for this job.")
    level = models.IntegerField(choices=ORDERING_CHOICES, default=0)
    location = models.CharField(max_length=100, default="")

    def get_absolute_url(self):
      return "/jobs/%s/" % self.url

    def __unicode__(self):
        return self.title



    objects = models.Manager()
    visible = VisibleJobManager()

jobs/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django import forms
from django.forms import ModelForm

from .models import Job

class JobForm(ModelForm):

    details = forms.CharField(label="Summary", widget=forms.Textarea, max_length="400", help_text="A brief description (Max 400 chars.)")

    class Meta:
        model = Job
        fields = ['title', 'company', 'location', 'contact_email', 'contact_phone', 'logo', 'details', 'lengthy_details', 'link']


    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'id-myform'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-5'
        super(JobForm, self).__init__(*args, **kwargs)

jobs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse

from .models import Job
from .forms import JobForm

def create(request):
    form = JobForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('job_thanks'))
    return render(request, 'jobs/create.html', {'form': form})

def list(request):
  return render(request, "jobs/index.html", {'jobs': Job.visible.all()})

def thanks(request):
  return render(request, "jobs/thanks.html")

def detail(request, slug):
  job = get_object_or_404(Job, url=slug)
  return render(request, "jobs/detail.html", {'job': job})

jobs/templates/jobs/create.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}
{% load generic_flatblocks %}

{% block content %}
    <section class="jobs">
      <div class="container">
<style type="text/css">
#id_details { height:40px;}
.help-block {margin-top:0px;}
input[type=text]{ margin-bottom: 10px !important}
</style>
<div class="row">
<h2>Submit your Job Posting</h2>

<div class="well">
  {% gblock "job-create-text" for "gblocks.Text" %}
</div>
{% crispy form %}
</div>

</div>
</section>
{% endblock %}

jobs/templates/jobs/detail.html
{% extends "frontend/base.html" %}
{% load markup_tags %}

{% block content %}
<section class="jobs">
  <div class="container">

    <div class="row">
      <div class="page-header no-border">
        <ol class="breadcrumb">
          <li><a href="..">Job Postings</a></li>
          <li>{{ job.title|safe }}</li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <div class="well">
          <p>
            {{ job.details }}
          </p>
          <br>
          <p>
          {% if job.link %}<p><a class="btn btn-sm btn-primary" href="{{ job.link }}" role="button">Apply</a>{% endif %}
          <a class="btn btn-sm btn-secondary" href=".." role="button">Back to Job Listings</a>
          </p>
        </div>
      </div>
      <div class="col-md-4">
        {% if job.logo %}<img class="featurette-image img-responsive center-block" src="{{job.logo.url }}" alt="{{job.title}}" width="300">{% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
          {{ job.lengthy_details|apply_markup:"markdown" }}
      </div>
    </div>
    <hr class="featurette-divider">
  </div>
</section>
{% endblock %}

jobs/templates/jobs/index.html
{% extends "frontend/base.html" %}
{% load generic_flatblocks %}

{% block content %}
<section class="jobs">
  <div class="container">
    <div class="row">
      <div class="page-header no-border">
        <ol class="breadcrumb">
          <li>Job Postings</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
      {% gblock "job-index-text" for "gblocks.Text" %}
      </div>
    </div>

    {% for job in jobs %}
    <div class="row">
      <div class="col-md-8">
        <h2 class="blue-title"><a href="{{ job.get_absolute_url }}">{{ job.title|safe }}</a></h2>
        <h3>{{ job.company }} ~ {{ job.location }}</h3>
        <p>{{ job.details|safe }}</p>
      </div>
      <div class="col-md-4">
        {% ifchanged job.logo %}
        {% if job.logo %}<img class="img-responsive" align="right" src="{{job.logo.url }}" alt="{{job.title}}" width="200">{% endif %}
        {% endifchanged %}
      </div>
    </div>
    <div class="row">
          <a class="btn btn-sm btn-success" href="{{ job.get_absolute_url }}" role="button">Learn More</a>
          {% if job.link %}<a class="btn btn-sm btn-primary" href="{{ job.link }}" role="button">Apply</a>{% endif %}
      <hr>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

jobs/templates/jobs/thanks.html
{% extends 'frontend/base.html' %}

{% block content %}
<section class="jobs">
  <div class="container">
    <div class="row">
      <h1>Thank you for submitting your Job Posting</h1>
      <p class="lead">The organizers will review your posting, check your sponsorship level, and mark it live within 24 hours.</p>
    </div>
  </div>
</div>
{% endblock %}